{
  config,
  lib,
  pkgs,
  inputs,
  siteLib,
  ...
}: let
  nixvirtLib = inputs.NixVirt.lib;
  apiAdvertiseAddress = siteLib.ip.kube-master;
  gateway = siteLib.ip.defaultGateway;
  # generated by assets/k8s/ca.crt
  caHash = "32b10d3c2eee5440d1d0a884aedc15345daf44047f5e1e94cc0a80c23351b5bf";
  sshKeys = siteLib.publicKeys;
in {
  imports = [
    ../../modules/sops
    ../../modules/hosts/fonts
    ../../modules/comin
    ../../modules/hosts/services/xrdp
    (siteLib.mkK8sMaster {
      inherit pkgs lib config nixvirtLib sshKeys apiAdvertiseAddress gateway;
      name = "kube-master";
      uuid = "c0ffee00-0001-0000-0000-000000000001";
      vcpu = 4;
      memoryGiB = 8;
      rootDiskSizeGiB = 30;
      bridge = "br0";
      ubuntuImage = siteLib.images.ubuntu-lts;
      ipAddress = "${siteLib.ip.kube-master}/23";
      podCIDR = "10.244.0.0/16";
    })
    (siteLib.mkK8sWorker {
      inherit pkgs lib config nixvirtLib sshKeys apiAdvertiseAddress caHash gateway;
      name = "kube-worker-emu-1";
      uuid = "c0ffee00-0001-0000-0000-000000000002";
      vcpu = 4;
      memoryGiB = 8;
      rootDiskSizeGiB = 30;
      bridge = "br0";
      ipAddress = "${siteLib.ip.kube-worker-emu-1}/23";
      ubuntuImage = siteLib.images.ubuntu-lts;
    })
    (siteLib.mkK8sWorker {
      inherit pkgs lib config nixvirtLib sshKeys apiAdvertiseAddress caHash gateway;
      name = "kube-worker-emu-2";
      uuid = "c0ffee00-0001-0000-0000-000000000003";
      vcpu = 4;
      memoryGiB = 8;
      rootDiskSizeGiB = 30;
      bridge = "br0";
      ipAddress = "${siteLib.ip.kube-worker-emu-2}/23";
      ubuntuImage = siteLib.images.ubuntu-lts;
    })
  ];

  boot.loader = {
    systemd-boot.enable = true;
    efi.canTouchEfiVariables = true;
  };

  environment = {
    # https://nix-community.github.io/home-manager/options.xhtml#opt-programs.bash.enableCompletion
    pathsToLink = [
      "/share/bash-completion"
    ];
  };

  networking = {
    hostName = "emu";
    useNetworkd = true;

    interfaces = {
      enp3s0.useDHCP = false;

      br0.ipv4.addresses = [
        {
          address = siteLib.ip.emu;
          prefixLength = 23;
        }
      ];
    };

    bridges.br0.interfaces = ["enp3s0"];

    defaultGateway = {
      address = siteLib.ip.defaultGateway;
      interface = "br0";
    };

    firewall = {
      enable = true;
      allowedTCPPorts = [3389];
      allowedUDPPorts = [3389];
    };

    nameservers = [
      "1.1.1.1"
      "8.8.8.8"
      "8.8.4.4"
    ];
  };

  nixpkgs.config.allowUnfree = true;

  programs.zsh.enable = true;

  users.users.momeemt = {
    isNormalUser = true;
    extraGroups = ["wheel" "docker"];
    shell = pkgs.zsh;
    hashedPasswordFile = config.sops.secrets.momeemt-password.path;
    openssh.authorizedKeys.keys = sshKeys;
  };

  services = {
    openssh = {
      enable = true;
      openFirewall = true;
      settings = {
        PasswordAuthentication = false;
      };
    };

    resolved = {
      enable = true;
      dnssec = "true";
      domains = ["~."];
      fallbackDns = ["1.1.1.1" "8.8.8.8" "8.8.4.4"];
      dnsovertls = "true";
    };

    cloudflared = {
      enable = true;
      tunnels = {
        "053a4ebe-82c3-485a-bc8b-f0768cbe1d11" = {
          credentialsFile = "${config.sops.secrets."cloudflared/emu.json".path}";
          ingress = {
            "emu.momee.mt" = {
              service = "ssh://localhost:22";
            };
            "s3.momee.mt" = {
              service = "http://localhost:9000";
            };
          };
          default = "http_status:404";
        };
        "b2b83e61-577c-45e7-b1c0-0961503e8d8d" = {
          credentialsFile = "${config.sops.secrets."cloudflared/emu-desktop.json".path}";
          ingress = {
            "emu-desktop.momee.mt" = {
              service = "rdp://localhost:3389";
            };
          };
          default = "http_status:404";
        };
      };
    };

    xserver = {
      enable = true;
      displayManager.gdm = {
        enable = true;
      };
      desktopManager.gnome.enable = true;
    };

    xrdp = {
      enable = true;
      defaultWindowManager = "${pkgs.gnome-session}/bin/gnome-session";
      openFirewall = true;
    };

    udev.packages = [pkgs.usb-blaster-udev-rules];
  };

  # https://github.com/NixOS/nixpkgs/issues/100390
  security.polkit.extraConfig = ''
    polkit.addRule(function(action, subject) {
        if (action.id == "org.freedesktop.login1.suspend" ||
            action.id == "org.freedesktop.login1.suspend-multiple-sessions" ||
            action.id == "org.freedesktop.login1.hibernate" ||
            action.id == "org.freedesktop.login1.hibernate-multiple-sessions")
        {
            return polkit.Result.NO;
        }
    });
  '';

  environment.gnome.excludePackages =
    (with pkgs; [
      gnome-photos
      gnome-tour
    ])
    ++ (with pkgs; [
      cheese
      gnome-music
      gnome-terminal
      gedit
      epiphany
      geary
      evince
      gnome-characters
      totem
      tali
      iagno
      hitori
      atomix
    ]);

  virtualisation = {
    docker.enable = true;

    libvirtd = {
      enable = true;
      qemu = {
        package = pkgs.qemu_kvm;
        runAsRoot = true;
      };
    };

    libvirt = {
      enable = true;
      verbose = true;
      connections."qemu:///system".pools = null;
    };
  };

  system.stateVersion = "25.05";
}
