creation_rules:
  - path_regex: "^secrets/.*$"
    age:
      # root@emu (used by sops-nix)
      - age1ey0measssqda4dp8cdt2ma8mx7muqzdlvt6v847h39rkfhvf9f6szugj5d
      # momeemt@emu
      - age1z4cupq3psq9fzfhmjlkjkd2320nn8y56gyu8z7u34633hpkgcfusnxd0t4
