#!/bin/bash

set -euo pipefail

ENVRC=".envrc"

if [ -f "$ENVRC" ]; then
  printf '%s' "$ENVRC founded. Are you sure to overwrite it? (y/N): "
  read -r answer || exit 1
  case "$answer" in
  y | Y) ;;
  *)
    echo "Aborted."
    exit 0
    ;;
  esac
fi

cat >"$ENVRC" <<'EOF'
# This file is auto-generated by ./assets/scripts/env.sh
use flake . --override-input tmux-nix path:./nix/flakes/tmux-nix
EOF

echo "[env.sh] Generated $ENVRC"
