# shellcheck disable=SC2148

set -euo pipefail

ENVRC=".envrc"

if [ -f "$ENVRC" ]; then
  printf '%s' "$ENVRC founded. Are you sure to overwrite it? (y/N): "
  read -r answer || exit 1
  case "$answer" in
  y | Y) ;;
  *)
    echo "Aborted."
    exit 0
    ;;
  esac
fi

cat >"$ENVRC" <<'EOF'
# This file is auto-generated by ./assets/scripts/env.sh
source_url "https://raw.githubusercontent.com/nix-community/nix-direnv/3.0.7/direnvrc" "sha256-bn8WANE5a91RusFmRI7kS751ApelG02nMcwRekC/qzc="
watch_dir nix/flakes
use flake
EOF

echo "[env.sh] Generated $ENVRC"
