# shellcheck disable=SC2148

set -euo pipefail

YES=false
for arg in "$@"; do
  case "$arg" in
  --yes)
    YES=true
    ;;
  *)
    echo "Usage: $0 [--yes]" >&2
    exit 1
    ;;
  esac
done

ROOT_ENVRC=".envrc"

if [ -f "$ROOT_ENVRC" ]; then
  if ! $YES; then
    printf '%s' "$ROOT_ENVRC founded. Are you sure to overwrite it? (y/N): "
    read -r answer || exit 1
    case "$answer" in
    y | Y) ;;
    *)
      echo "Aborted."
      exit 0
      ;;
    esac
  else
    echo "[env.sh] Overwriting existing $ROOT_ENVRC (--yes)"
  fi
fi

cat >"$ROOT_ENVRC" <<'EOF'
# This file is auto-generated by ./assets/scripts/env.sh
source_url "https://raw.githubusercontent.com/nix-community/nix-direnv/3.0.7/direnvrc" "sha256-bn8WANE5a91RusFmRI7kS751ApelG02nMcwRekC/qzc="
watch_dir nix/flakes

if [ "${CHILD_ENVRC-0}" != "1" ]; then
  use flake
fi
EOF

echo "[env.sh] Generated $ROOT_ENVRC"

while IFS= read -r devShell; do
  dir=$(dirname "$devShell")
  envrc_path="$dir/.envrc"

  if [ "$dir" = "." ]; then
    continue
  fi

  clean_dir=${dir#./}
  name=$(basename "$clean_dir")

  IFS='/' read -r -a parts <<<"$clean_dir"
  up=""
  for _ in "${parts[@]}"; do
    up="../$up"
  done
  rel_flake="${up}#${name}"

  if [ -f "$envrc_path" ]; then
    if $YES; then
      echo "[env.sh] Overwriting existing $envrc_path (--yes)"
    else
      printf '%s' "$envrc_path found. Overwrite? (y/N): "
      if ! read -r answer </dev/tty; then
        echo "[env.sh] Failed to read answer, skip $envrc_path" >&2
        continue
      fi
      case "$answer" in
      y | Y) ;;
      *)
        echo "[env.sh] Skip $envrc_path"
        continue
        ;;
      esac
    fi
  fi

  cat >"$envrc_path" <<EOF
# This file is auto-generated by ./assets/scripts/env.sh
export CHILD_ENVRC=1
source_up
unset CHILD_ENVRC

watch_file devShell.nix
use flake $rel_flake
EOF

  echo "[env.sh] Generated $envrc_path"
done < <(find . -name devShell.nix -print)
