{
  public_keys = [
    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFEZxgazfYTiSMF3sWGFp8sK8bttFU5tfY+cFd6eEX0T momeemt@uguisu"
    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIC6OOOiSae2Vm4K3swSzxgZVQOxsZ5rlh/DOHcHEyULk Generated By Termius"
  ];
}
