{
  config,
  lib,
  pkgs,
  inputs,
  siteLib,
  ...
}: let
  nixvirtLib = inputs.NixVirt.lib;
  sshKeys = (import ../../system/ssh.nix).public_keys;
  apiAdvertiseAddress = "192.168.32.200";
  gateway = "192.168.32.1";
  # generated by assets/k8s/ca.crt
  caHash = "32b10d3c2eee5440d1d0a884aedc15345daf44047f5e1e94cc0a80c23351b5bf";
in {
  imports = [
    ../../modules/sops
    ../../modules/fonts
    ../../modules/comin
    (siteLib.mkK8sWorker {
      inherit pkgs lib config nixvirtLib sshKeys apiAdvertiseAddress caHash gateway;
      name = "kube-worker-shime-1";
      uuid = "c0ffee00-0002-0000-0000-000000000001";
      vcpu = 4;
      memoryGiB = 8;
      rootDiskSizeGiB = 30;
      bridge = "br0";
      ubuntuImage = siteLib.images.ubuntu-lts;
      ipAddress = "192.168.32.203/23";
    })
  ];

  nix = {
    settings = {
      experimental-features = [
        "nix-command"
        "flakes"
      ];
    };
  };

  environment = {
    # https://nix-community.github.io/home-manager/options.xhtml#opt-programs.bash.enableCompletion
    pathsToLink = [
      "/share/bash-completion"
    ];
  };

  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  i18n.defaultLocale = "ja_JP.UTF-8";
  console = {
    useXkbConfig = true;
  };

  time.timeZone = "Asia/Tokyo";

  networking = {
    hostName = "shime";
    useNetworkd = true;
    firewall = {
      enable = true;
      trustedInterfaces = ["tailscale0"];
    };
    nameservers = [
      "1.1.1.1"
      "8.8.8.8"
      "8.8.4.4"
    ];
    interfaces.enp4s0.useDHCP = false;
    bridges.br0.interfaces = ["enp4s0"];
    interfaces.br0.useDHCP = true;
  };

  nixpkgs.config.allowUnfreePredicate = pkg:
    builtins.elem (lib.getName pkg) [
      "copilot.vim"
      "google-chrome"
      "spotify"
      "discord"
      "todoist-electron"
      "vscode"
      "vscode-extension-ms-vscode-remote-remote-containers"
      "vscode-extension-ms-vscode-remote-remote-ssh"
      "vscode-extension-ms-vscode-remote-remote-ssh-edit"
    ];

  users.users.momeemt = {
    isNormalUser = true;
    extraGroups = ["wheel" "docker" "libvirtd"];
    shell = pkgs.zsh;
    openssh.authorizedKeys.keys = (import ../../system/ssh.nix).public_keys;
  };

  programs = {
    nix-ld.enable = true;
    zsh = {
      enable = true;
      enableCompletion = false;
    };
  };

  services.tailscale = {
    enable = true;
    openFirewall = true;
  };

  services.openssh = {
    enable = true;
    settings.PasswordAuthentication = false;
  };

  services.vscode-server = {
    enable = true;
    enableFHS = true;
  };

  virtualisation.libvirtd = {
    enable = true;
    qemu = {
      package = pkgs.qemu_kvm;
      runAsRoot = true;
    };
  };

  virtualisation.libvirt = {
    enable = true;
    verbose = true;
    connections."qemu:///system".pools = null;
  };

  programs.virt-manager.enable = true;

  hardware.graphics = {
    enable = true;
    extraPackages = [pkgs.mesa];
  };

  system.stateVersion = "25.05";
}
