export EDITOR='vim'
export VISUAL='vim'
export LANG='ja_JP.UTF-8'

HISTFILE=~/.zsh_history
HISTSIZE=10000
SAVEHIST=10000
setopt extended_history
setopt hist_ignore_dups
setopt share_history
setopt hist_reduce_blanks

