{
  config,
  lib,
  pkgs,
  inputs,
  siteLib,
  ...
}: let
  nixvirtLib = inputs.NixVirt.lib;
  sshKeys = siteLib.publicKeys;
  apiAdvertiseAddress = "192.168.32.200";
  gateway = "192.168.32.1";
  # generated by assets/k8s/ca.crt
  caHash = "32b10d3c2eee5440d1d0a884aedc15345daf44047f5e1e94cc0a80c23351b5bf";
in {
  imports = [
    ../../modules/sops
    ../../modules/hosts/fonts
    ../../modules/comin
    (siteLib.mkK8sWorker {
      inherit pkgs lib config nixvirtLib sshKeys apiAdvertiseAddress caHash gateway;
      name = "kube-worker-shime-1";
      uuid = "c0ffee00-0002-0000-0000-000000000001";
      vcpu = 4;
      memoryGiB = 8;
      rootDiskSizeGiB = 30;
      bridge = "br0";
      ubuntuImage = siteLib.images.ubuntu-lts;
      ipAddress = "192.168.32.203/23";
    })
  ];

  nix = {
    settings = {
      experimental-features = [
        "nix-command"
        "flakes"
      ];
    };
  };

  environment = {
    # https://nix-community.github.io/home-manager/options.xhtml#opt-programs.bash.enableCompletion
    pathsToLink = [
      "/share/bash-completion"
    ];
  };

  boot.loader = {
    systemd-boot.enable = true;
    efi.canTouchEfiVariables = true;
  };

  i18n.defaultLocale = "ja_JP.UTF-8";
  console = {
    useXkbConfig = true;
  };

  time.timeZone = "Asia/Tokyo";

  networking = {
    hostName = "shime";
    useNetworkd = true;
    firewall = {
      enable = true;
      trustedInterfaces = ["tailscale0"];
    };
    nameservers = [
      "1.1.1.1"
      "8.8.8.8"
      "8.8.4.4"
    ];
    interfaces = {
      enp4s0.useDHCP = false;
      br0.useDHCP = true;
    };
    bridges.br0.interfaces = ["enp4s0"];
  };

  nixpkgs.config.allowUnfree = true;

  users.users.momeemt = {
    isNormalUser = true;
    extraGroups = ["wheel" "docker" "libvirtd"];
    shell = pkgs.zsh;
    openssh.authorizedKeys.keys = sshKeys;
  };

  programs = {
    nix-ld.enable = true;
    zsh = {
      enable = true;
      enableCompletion = false;
    };
  };

  services = {
    tailscale = {
      enable = true;
      openFirewall = true;
    };

    openssh = {
      enable = true;
      settings.PasswordAuthentication = false;
    };

    vscode-server = {
      enable = true;
      enableFHS = true;
    };
  };

  virtualisation = {
    libvirtd = {
      enable = true;
      qemu = {
        package = pkgs.qemu_kvm;
        runAsRoot = true;
      };
    };

    libvirt = {
      enable = true;
      verbose = true;
      connections."qemu:///system".pools = null;
    };
  };

  hardware.graphics = {
    enable = true;
    extraPackages = [pkgs.mesa];
  };

  system.stateVersion = "25.05";
}
