---
name: "CI"
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
jobs:
  flake-check:
    permissions:
      contents: read
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false
      - uses: DeterminateSystems/determinate-nix-action@b3e3f405539b332fcb96794525f35fb10c230baa # v3.13.2
      - run: nix flake check --all-systems
  nix-build:
    if: github.event_name == 'pull_request'
    permissions:
      contents: read
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: ciConfigurations.emu.config.system.build.toplevel
            os: ubuntu-24.04
          - target: ciConfigurations.shime.config.system.build.toplevel
            os: ubuntu-24.04
          - target: darwinConfigurations.uguisu.system
            os: macos-15
          - target: homeConfigurations.example.activationPackage
            os: ubuntu-24.04
    steps:
      - uses: easimon/maximize-build-space@fc881a613ad2a34aca9c9624518214ebc21dfc0c # v10
        if: runner.os == 'Linux'
        with:
          root-reserve-mb: 4096
          swap-size-mb: 1024
          build-mount-path: /nix
          remove-dotnet: true
          remove-android: true
          remove-haskell: true
          remove-codeql: true
          remove-docker-images: true
      - name: Fix /nix ownership
        if: runner.os == 'Linux'
        run: sudo chown root:root /nix
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false
      - uses: DeterminateSystems/determinate-nix-action@b3e3f405539b332fcb96794525f35fb10c230baa # v3.13.2
      - run: nix build .#${{ matrix.target }} --no-link
  container-build:
    if: github.event_name == 'pull_request'
    permissions:
      contents: read
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false
      - uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1
      - uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        with:
          context: .
          file: .devcontainer/Dockerfile
          platforms: linux/amd64
          push: false
