---
name: "Deploy Obsidian"
on:
  push:
    branches:
      - '**'
    paths:
      - ".github/workflows/obsidian.yaml"
      - "nix/flakes/default.nix"
      - "nix/flakes/packages.nix"
      - "packages/o/obsidian/**"
  pull_request:
    branches:
      - '**'
    paths:
      - ".github/workflows/obsidian.yaml"
      - "nix/flakes/default.nix"
      - "nix/flakes/packages.nix"
      - "packages/o/obsidian/**"
  workflow_dispatch:
permissions:
  contents: read
  issues: write
  pull-requests: write
concurrency:
  group: obsidian-pages-${{ github.ref }}
  cancel-in-progress: true
jobs:
  deploy:
    if: >-
      github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: cachix/install-nix-action@8aa03977d8d733052d78f4e008a241fd1dbf36b3 # v31.10.6
      - name: Setup Attic cache
        if: >-
          github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository
        uses: ryanccn/attic-action@5635a15ef0c5462194ffbd05d1daeddc74625c3a # v0.5.0
        with:
          endpoint: ${{ secrets.ATTIC_ENDPOINT }}
          cache: ${{ secrets.ATTIC_CACHE }}
          token: ${{ secrets.ATTIC_TOKEN }}
      - name: Build Obsidian
        run: nix build .#obsidian
      - name: Deploy to Cloudflare Pages
        id: deploy
        uses: ./.github/actions/deploy-cloudflare-pages
        with:
          directory: result
          project-name: obsidian-momee-mt
          domain: obsidian.momee.mt
          cloudflare-account-id: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          cloudflare-api-token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      - name: Comment preview URL
        if: github.event_name == 'pull_request'
        uses: ./.github/actions/comment-preview-url
        with:
          preview-name: "Obsidian"
          deployment-url: ${{ steps.deploy.outputs.deployment_url }}
          deploy-branch: ${{ steps.deploy.outputs.deploy_branch }}
          github-token: ${{ github.token }}
          pr-number: ${{ github.event.pull_request.number }}
          commit-sha: ${{ github.sha }}
