---
name: "Deploy Portfolio"
on:
  push:
    branches:
      - '**'
    paths:
      - ".github/workflows/portfolio.yaml"
      - "flake.lock"
      - "flake.nix"
      - "nix/flakes/default.nix"
      - "nix/flakes/devShells.nix"
      - "nix/flakes/packages.nix"
      - "packages/p/portfolio/**"
  pull_request:
    branches:
      - '**'
    paths:
      - ".github/workflows/portfolio.yaml"
      - "flake.lock"
      - "flake.nix"
      - "nix/flakes/default.nix"
      - "nix/flakes/devShells.nix"
      - "nix/flakes/packages.nix"
      - "packages/p/portfolio/**"
  workflow_dispatch:
permissions:
  contents: read
  issues: write
  pull-requests: write
concurrency:
  group: portfolio-pages-${{ github.ref }}
  cancel-in-progress: true
env:
  PORTFOLIO_DOMAIN: momee.mt
  PORTFOLIO_PAGES_PROJECT_NAME: momee-mt
jobs:
  deploy:
    if: >-
      github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: DeterminateSystems/determinate-nix-action@b3e3f405539b332fcb96794525f35fb10c230baa # v3.13.2
      - name: Build Portfolio
        run: nix build .#portfolio
      - name: Deploy to Cloudflare Pages
        id: deploy
        uses: ./.github/actions/deploy-cloudflare-pages
        with:
          directory: result
          project-name: ${{ env.PORTFOLIO_PAGES_PROJECT_NAME }}
          domain: ${{ env.PORTFOLIO_DOMAIN }}
          cloudflare-account-id: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          cloudflare-api-token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      - name: Comment preview URL
        if: github.event_name == 'pull_request'
        uses: ./.github/actions/comment-preview-url
        with:
          preview-name: "Portfolio"
          deployment-url: ${{ steps.deploy.outputs.deployment_url }}
          deploy-branch: ${{ steps.deploy.outputs.deploy_branch }}
          github-token: ${{ github.token }}
          pr-number: ${{ github.event.pull_request.number }}
          commit-sha: ${{ github.sha }}
